name: Build Docker Images
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: node-yeoman ${{ matrix.node }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build nystudio107/node-yeoman:${{ matrix.node }}-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: nystudio107/node-yeoman:${{ matrix.node }}-alpine
          build-args: |
            TAG=${{ matrix.node }}-alpine
